# Generated by Django 4.2.16 on 2024-11-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
            ],
            options={
                'verbose_name': 'пациент',
                'verbose_name_plural': 'пациенты',
            },
        ),
    ]
