# Generated by Django 4.2.16 on 2024-11-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_image_category_image_tags_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="описание"),
        ),
        migrations.AddField(
            model_name="image",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="мета данные"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="название"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/", verbose_name="изображение"),
        ),
    ]
