# Generated by Django 4.2.16 on 2024-11-23 14:17

from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_image_description_image_metadata_image_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=images.models.Tiles._upload_to)),
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="images.image"
                    ),
                ),
            ],
        ),
    ]
